import { Moon, Utensils, Target, Brain } from 'lucide-react';

interface SmartSuggestionsProps {
  suggestions: {
    sleep: string;
    feeding: string;
    routine: string;
  };
  childName: string;
}

export function SmartSuggestions({ suggestions, childName }: SmartSuggestionsProps) {
  return (
    <section>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900 flex items-center">
            <Brain className="w-6 h-6 mr-2 text-indigo-600" />
            Smart Suggestions for Today
          </h2>
          <p className="text-gray-600 mt-1">Generated by your AI co-pilot based on {childName}'s patterns</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="group bg-white/70 backdrop-blur-xl rounded-2xl p-6 shadow-lg border border-white/20 hover:shadow-2xl transition-all transform hover:-translate-y-1">
          <div className="flex items-center justify-between mb-4">
            <div className="w-12 h-12 bg-gradient-to-br from-indigo-100 to-indigo-200 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
              <Moon className="w-6 h-6 text-indigo-600" />
            </div>
            <span className="text-xs font-semibold text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">
              Sleep Coach
            </span>
          </div>
          <h3 className="font-bold text-gray-900 mb-2 text-lg">Tonight's Sleep Tip</h3>
          <p className="text-gray-600 text-sm leading-relaxed mb-4">
            {suggestions.sleep || 'Loading personalized sleep advice...'}
          </p>
          <button
            onClick={() => {
              window.history.pushState({}, '', '/chat');
              window.dispatchEvent(new PopStateEvent('popstate'));
              setTimeout(() => {
                const input = document.querySelector('textarea') as HTMLTextAreaElement;
                if (input) {
                  input.value = 'Show me a personalized sleep plan for my baby';
                  input.focus();
                }
              }, 100);
            }}
            className="text-indigo-600 font-semibold text-sm hover:text-indigo-700 transition-colors inline-block"
          >
            See sleep plan →
          </button>
        </div>

        <div className="group bg-white/70 backdrop-blur-xl rounded-2xl p-6 shadow-lg border border-white/20 hover:shadow-2xl transition-all transform hover:-translate-y-1">
          <div className="flex items-center justify-between mb-4">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-100 to-purple-200 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
              <Utensils className="w-6 h-6 text-purple-600" />
            </div>
            <span className="text-xs font-semibold text-purple-600 bg-purple-50 px-3 py-1 rounded-full">
              Feeding Coach
            </span>
          </div>
          <h3 className="font-bold text-gray-900 mb-2 text-lg">Feeding Rhythm</h3>
          <p className="text-gray-600 text-sm leading-relaxed mb-4">
            {suggestions.feeding || 'Loading feeding recommendations...'}
          </p>
          <button
            onClick={() => {
              window.history.pushState({}, '', '/chat');
              window.dispatchEvent(new PopStateEvent('popstate'));
              setTimeout(() => {
                const input = document.querySelector('textarea') as HTMLTextAreaElement;
                if (input) {
                  input.value = 'Give me detailed feeding advice and guidance';
                  input.focus();
                }
              }, 100);
            }}
            className="text-purple-600 font-semibold text-sm hover:text-purple-700 transition-colors inline-block"
          >
            Learn more →
          </button>
        </div>

        <div className="group bg-white/70 backdrop-blur-xl rounded-2xl p-6 shadow-lg border border-white/20 hover:shadow-2xl transition-all transform hover:-translate-y-1">
          <div className="flex items-center justify-between mb-4">
            <div className="w-12 h-12 bg-gradient-to-br from-pink-100 to-pink-200 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
              <Target className="w-6 h-6 text-pink-600" />
            </div>
            <span className="text-xs font-semibold text-pink-600 bg-pink-50 px-3 py-1 rounded-full">
              Routine Planner
            </span>
          </div>
          <h3 className="font-bold text-gray-900 mb-2 text-lg">Today's Routine Focus</h3>
          <p className="text-gray-600 text-sm leading-relaxed mb-4">
            {suggestions.routine || 'Loading activity suggestions...'}
          </p>
          <button
            onClick={() => {
              window.history.pushState({}, '', '/chat');
              window.dispatchEvent(new PopStateEvent('popstate'));
              setTimeout(() => {
                const input = document.querySelector('textarea') as HTMLTextAreaElement;
                if (input) {
                  input.value = 'Suggest age appropriate activities and routines for my baby';
                  input.focus();
                }
              }, 100);
            }}
            className="text-pink-600 font-semibold text-sm hover:text-pink-700 transition-colors inline-block"
          >
            View activities →
          </button>
        </div>
      </div>
    </section>
  );
}
